# Generated by Django 4.1.7 on 2023-06-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="url",
            field=models.CharField(
                blank=True, max_length=127, unique=True, verbose_name="url"
            ),
        ),
    ]
